version: '2'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - ./src:/var/www/html
        ports: 
            - 9007:80
        links:
            - wordpress
        restart: always
    wordpress:
        image: wordpress:4.9.7-php7.1-fpm
        volumes: 
            - ./src:/var/www/html
            - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            - WORDPRESS_DB_NAME=wpdb    
            - WORDPRESS_TABLE_PREFIX=wp_    
            - WORDPRESS_DB_HOST=mysql    
            - WORDPRESS_DB_PASSWORD=Abc@#123456
        links:
            - mysql
        restart: always
    mysql: 
        image: mysql:latest
        volumes: 
            - ./data/db-data2:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=Abc@#123456
            - MYSQL_DATABASE=wpdb
        restart: always
  